// sw.js
self.addEventListener('install', (e) => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));

// 페이지(index.html)에서 보낸 알림 명령 수신
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SHOW_NOTIFICATION') {
        const { title, body } = event.data;
        self.registration.showNotification(title, {
            body: body,
            icon: 'https://cdn-icons-png.flaticon.com/512/311/311074.png',
            vibrate: [200, 100, 200],
            badge: 'https://cdn-icons-png.flaticon.com/512/311/311074.png',
            tag: 'smart-alarm-sync',
            renotify: true
        });
    }
});                                                                                                                                                                                                                                a.notifiedBefore = true;
                                                                                                                                                                                                                                                changed = true;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                        // 2. 기준 시간 도달 시 시간 갱신
                                                                                                                                                                                                                                                                                    if (now >= alarmTime) {
                                                                                                                                                                                                                                                                                                    const intervalMs = (parseInt(a.interval) || 300) * 1000;
                                                                                                                                                                                                                                                                                                                    let nextTarget = alarmTime;
                                                                                                                                                                                                                                                                                                                                    while (nextTarget <= now) {
                                                                                                                                                                                                                                                                                                                                                        nextTarget = new Date(nextTarget.getTime() + intervalMs);
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        a.time = nextTarget.toISOString();
                                                                                                                                                                                                                                                                                                                                                                                                        a.notifiedBefore = false;
                                                                                                                                                                                                                                                                                                                                                                                                                        changed = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 시간이 갱신되었다면 페이지에 알림 (페이지가 열려있을 때만 수신됨)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (changed) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        broadcastChange();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function showNoti(title, body) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.registration.showNotification(title, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: body,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        icon: 'https://cdn-icons-png.flaticon.com/512/311/311074.png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vibrate: [200, 100, 200],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tag: 'smart-alarm-' + Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                renotify: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function broadcastChange() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.clients.matchAll().then(clients => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clients.forEach(client => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            client.postMessage({ type: 'UPDATE_ALARM_LIST', alarms: alarmList });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
